A standard is not always encoded as a single document
finos/standards-project-blueprint pull request #11
Opened 2022-05-06 18:05 UTC by kriswest

... and might instead be formed by a collection of web pages and other artifacts such as source code files (as is the case with FDC3).

We've been advised (on the FINOS/FDC3 standard project) that although the convention used by ANSI, ISO and ECMA is for a standard to be encoded as a single document, this is not the case for other organisations such the W3C or IETF (among others), which are modern and web-based. This is also the case for FDC3 where the standard is formed by a number of webpages (forming part of the same website), supported by source code and schema files.

However, there is language in the CSL 1.0 (specifically in the governance section) that specifically refers to a single document. This PR seeks modify that language to allow it to apply to other artifacts such as webpages and source code files that are developed under and governed by the Community Specification.

We could of course make these changes in our own copy of these documents, however, we both desire to remain aligned with the CSL and FINOS' standards project governance.

This PR has also been raised on the CSL repository upstream (https://github.com/CommunitySpecification/Community_Specification/pull/10), but they've advised that we can make this change within FINOS and they'll consider when they next meet.

2022-05-06 18:05 UTC, kriswest commented
@mindthegab

2022-06-17 00:27 UTC, mindthegab requested changes
This is good for me if you address the change. I can bring it to the Board next time around.

2022-06-17 00:27 UTC, mindthegab commented on governance-documents/5._Governance.md
> +This document provides the governance policy for specifications and other documents or artifacts, such as a web page or source code, developed using the Community Specification process in a repositor
I think we should keep source code out of this - because the underlying source code is already licensed under Apache per [CSL](https://github.com/finos/standards-project-blueprint/blob/master/governance-documents/1._Community_Specification_License-v1.md?plain=1#L51).

2022-06-17 07:55 UTC, kriswest commented on governance-documents/5._Governance.md
> +This document provides the governance policy for specifications and other documents or artifacts, such as a web page or source code, developed using the Community Specification process in a repositor
@mindthegab There's sourcecode for things like the FDC3 workbench and then there's the sourcecode for the standard interfaces for the API, then schemas and typescript sourcecode for the standard context types. These are referenced in the standard docs here: https://fdc3.finos.org/docs/api/spec#apis and here: https://fdc3.finos.org/docs/context/spec#standard-context-types

How about this instead:
```suggestion
This document provides the governance policy for specifications and other documents or artefacts, such as web pages, schemas or interface definitions developed using the Community Specification process in a repository (each a “Working Group”).  Each Working Group must adhere to the requirements in this document.

```

2022-06-23 10:17 UTC, kriswest commented on governance-documents/5._Governance.md
> +This document provides the governance policy for specifications and other documents or artifacts, such as a web page or source code, developed using the Community Specification process in a repositor
Applied the update @mindthegab

2022-07-15 14:07 UTC, kriswest commented
Discussed this today with @scooter99boston and @robmoffat and understand that the change proposed would be difficult. For FDC3s purposes the abstract page for the standard version (which links to the rest of the documents, all held in the same repository) can be used as the document and linked to at specific versions via a github tag.

Hence, I'll go ahead and close this (and have closed (https://github.com/CommunitySpecification/Community_Specification/pull/10) with the same).

We'll await a further change to the FINOS fork of the CSL (@robmoffat has details) before we complete the adoption of it in FDC3 (to save making the changes twice). Hopefully that won't take long.

2022-07-15 14:07 UTC, kriswest commented
Discussed this today with @scooter99boston and @robmoffat and understand that the change proposed would be difficult. For FDC3s purposes the abstract page for the standard version (which links to the rest of the documents, all held in the same repository) can be used as the document and linked to at specific versions via a github tag.

Hence, I'll go ahead and close this (and have closed (https://github.com/CommunitySpecification/Community_Specification/pull/10) with the same).

We'll await a further change to the FINOS fork of the CSL (@robmoffat has details) before we complete the adoption of it in FDC3 (to save making the changes twice). Hopefully that won't take long.

2022-07-15 14:07 UTC, closed without merging